### ISSUE TITLE
ERROR_DELAY_LOAD_FAILED when running winfsp_init

### ISSUE THREAD

**Issue by ccrutchf** [SnowflakePowered/winfsp-rs#13]
I am receiving `Result::unwrap() on an Err value: WIN32(WIN32_ERROR(1285))` when attempting to run `winfsp_init`.  I am using the default configuration, not a delayed load, so I am unsure where this error comes from.

Are there logs that I can look at to help debug this issue?

Thanks!

**Comment by chyyran** [comment]
WinFSP only supports delayload as per the tutorial: https://winfsp.dev/doc/WinFsp-Tutorial/

You *need* to put 

```rust
winfsp::build::winfsp_link_delayload();
```

in your build.rs
